const router = require('express').Router()
const RegisterService = require('../../services/RegisterService')
const PatientService = require('../../services/PatientService')
const QueueSessionService = require('../../services/QueueSessionService')
const RegisterValidator = require('../../validator/RegisterValidator')
const RegisterHandler = require('./controller')
const { verifyToken } = require('../../middleware/AuthHandler')
const axios = require('axios')
const ExcelJS = require('exceljs')
const csrf = require('csurf')

const csrfProtection = csrf()

const registerService = new RegisterService()
const patientService = new PatientService()
const queueSessionService = new QueueSessionService()
const registerHandler = new RegisterHandler(registerService, RegisterValidator, axios, ExcelJS, patientService, queueSessionService)

router.post('/', registerHandler.postRegisterHandler)
router.post('/new', registerHandler.postRegisterNewHandler)
router.get('/', verifyToken(), registerHandler.getAllRegisterHandler)
router.get('/search', verifyToken(), registerHandler.getPatientByNameOrNikHandler)
router.get('/export/monthly', verifyToken(['admin']), registerHandler.getExportExcelMonthly)
router.get('/export/daily', verifyToken(['admin','pendaftaran']), registerHandler.getExportExcelDaily)
router.get('/export/logbook', verifyToken(['admin']), registerHandler.getExportExcelLogbook)
router.post('/complete', verifyToken(), csrfProtection, registerHandler.postCompleteRegisterHandler)
router.get('/finance/monthly', verifyToken(['admin']), registerHandler.getAllRegisterByYearMonthHandler)
router.get('/finance/daily', verifyToken(['admin','pendaftaran']), registerHandler.getAllRegisterByRangeDateHandler)
router.get('/finance/:year', verifyToken(['admin']), registerHandler.getFinanceByYearHandler)
router.post('/notif/:id', verifyToken(), csrfProtection, registerHandler.postSendWhatsappMessage)
router.get('/:id', verifyToken(), registerHandler.getRegisterByIdHandler)
router.delete('/:id', verifyToken(), csrfProtection, registerHandler.deleteRegisterByIdHandler)
router.put('/:id', verifyToken(), csrfProtection, registerHandler.updateRegisterByIdHandler)

module.exports = router