const router = require('express').Router()
const RegisterService = require('../../services/RegisterService')
const RegisterValidator = require('../../validator/RegisterValidator')
const RegisterHandler = require('./controller')
const { verifyToken, verifyAdminToken } = require('../../middleware/AuthHandler')
const axios = require('axios')
const ExcelJS = require('exceljs')

const registerService = new RegisterService()
const registerHandler = new RegisterHandler(registerService, RegisterValidator, axios, ExcelJS)

router.post('/', registerHandler.postRegisterHandler)
router.get('/', verifyToken, registerHandler.getAllRegisterHandler)
router.get('/patient/monthly', verifyAdminToken, registerHandler.getAllRegisterByYearMonthHandler)
router.get('/patient/daily', verifyAdminToken, registerHandler.getAllRegisterByRangeDateHandler)
router.get('/search', verifyToken, registerHandler.getPatientByNameOrNikHandler)
router.get('/patient/:nik', verifyToken, registerHandler.getRegisterByNikHandler)
router.get('/export/monthly', verifyAdminToken, registerHandler.getExportExcelMonthly)
router.get('/export/daily', verifyAdminToken, registerHandler.getExportExcelDaily)
router.post('/complete', verifyToken, registerHandler.postCompleteRegisterHandler)
router.get('/finance/:year', verifyAdminToken, registerHandler.getFinanceByYearHandler)
router.post('/notif/:id', verifyToken, registerHandler.postSendWhatsappMessage)
router.get('/:id', verifyToken, registerHandler.getRegisterByIdHandler)
router.delete('/:id', verifyToken, registerHandler.deleteRegisterByIdHandler)
router.put('/:id', verifyToken, registerHandler.updateRegisterByIdHandler)

module.exports = router