const router = require('express').Router()
const RegisterService = require('../../services/RegisterService')
const PatientService = require('../../services/PatientService')
const RegisterValidator = require('../../validator/RegisterValidator')
const RegisterHandler = require('./controller')
const { verifyToken, verifyAdminToken, verifyAdminOrPendaftaranToken } = require('../../middleware/AuthHandler')
const axios = require('axios')
const ExcelJS = require('exceljs')

const registerService = new RegisterService()
const patientService = new PatientService()
const registerHandler = new RegisterHandler(registerService, RegisterValidator, axios, ExcelJS, patientService)

router.post('/', registerHandler.postRegisterHandler)
router.post('/new', registerHandler.postRegisterNewHandler)
router.get('/', verifyToken, registerHandler.getAllRegisterHandler)
router.get('/search', verifyToken, registerHandler.getPatientByNameOrNikHandler)
router.get('/export/monthly', verifyAdminToken, registerHandler.getExportExcelMonthly)
router.get('/export/daily', verifyAdminOrPendaftaranToken, registerHandler.getExportExcelDaily)
router.post('/complete', verifyToken, registerHandler.postCompleteRegisterHandler)
router.get('/finance/monthly', verifyAdminToken, registerHandler.getAllRegisterByYearMonthHandler)
router.get('/finance/daily', verifyAdminOrPendaftaranToken, registerHandler.getAllRegisterByRangeDateHandler)
router.get('/finance/:year', verifyAdminToken, registerHandler.getFinanceByYearHandler)
router.post('/notif/:id', verifyToken, registerHandler.postSendWhatsappMessage)
router.get('/:id', verifyToken, registerHandler.getRegisterByIdHandler)
router.delete('/:id', verifyToken, registerHandler.deleteRegisterByIdHandler)
router.put('/:id', verifyToken, registerHandler.updateRegisterByIdHandler)

module.exports = router